### ISSUE TITLE
dark mode not working

### ISSUE THREAD

**Issue by vincentf123** [Leberkasrechner/Leberkasrechner#8]
![image](https://github.com/Leberkasrechner/Leberkasrechner/assets/147273663/e600e778-b1eb-417d-98b1-8992422f684e)
Firefox is not able to connect to leberkasrechner.de if dark mode in enabled.

**Comment by Phipsiart** [comment]
I noticed that I forgot to enable http, only https was enabled. I added the http server block in the nginx config. It should work now.
![grafik](https://github.com/Leberkasrechner/Leberkasrechner/assets/98510944/941027b3-6274-40da-a530-ed2ffb525a01)
![grafik](https://github.com/Leberkasrechner/Leberkasrechner/assets/98510944/dbc46264-34e1-4e3f-b987-19221a803320)

thanks again @vincentf123  for reporting this issue.
